### ISSUE TITLE
New proposal discovery system

### ISSUE THREAD

**Issue by septs** [tc39/dataset#2]
Step: 
1. Search topic `tc39-proposal`
    see <https://github.com/search?q=topic%3Atc39-proposal>
2. Get Content (filename tbd)
3. Use individual proposal schema parse it
4. Record to dataset

**Comment by septs** [comment]
CC @codehag

**Comment by ljharb** [comment]
The non-prose source of truth is not the individual repos, but only the proposals repo itself (which represents the notes which represent plenary consensus, ofc). Adding a topic to each individual repo seems fine, but i don’t think data should be scraped from individual repos (which are often much slower to update than the main list anyways)

**Comment by codehag** [comment]
Sometimes the repos themselves are out of date, but the proposals repository is usually up to date, as more people are paying attention to it than individual repositories.
