### ISSUE TITLE
TC39 Proposal Linter (GitHub Action)

### ISSUE THREAD

**Issue by septs** [tc39/dataset#3]
1. Check repository
    - assert repository name, `proposal-` prefix
    - assert repository topics, e.q: `tc39-proposal`
2. Check metadata compliance
    1. verify schema
    2. assert `tags` (must include `ECMA-262` or `ECMA-402`, etc)
    3. assert `stage` (non tc39 org, stage can only be `0`)
    4. assert `id` (must equal repository name)
    5. assert `champions` (must be [delegates](https://github.com/tc39/notes/blob/master/delegates.txt))
    6. assert `notes` (url must available)
    7. assert `tests` (url must available)
    8. assert `snippets` (file-path must exist)
    9. assert `polyfills` (url must available)
3. Need new repo
    `tc39/proposal-linter-action`

**Comment by codehag** [comment]
When checking the metadata compliance, will this be graded according to proposal stage? For example, tests are not accepted into the test 262 repository until stage 3, so early stage 3 and earlier proposals will fail that check. If it wasn't your intention already, then i would suggest that most of these fields, other than stage and authors (stage 0 proposals do not necessarily have a champion yet) are optional. Enforcing all of the fields would also have unintended consequences, such as eager solutions without adequate exploration of the problem space. 

On the topic of action repos. We will need these to realize the data sync plan presented last meeting. I have been thinking about this as well. Maybe we can have the prefix `action` and say `tc39/ation-<name>`, this way we won't collide with proposals.

**Comment by codehag** [comment]
One thought I had, which might be incorporated into this Linter, or perhaps another one, is to automatically check if MDN browser compat data already exists, or if it needs to be made. MDN's browser compat data is consumed by specifications such as whatwg, and we might be able to do the same at some later date. Here is an example in-spec: https://html.spec.whatwg.org/#custom-handlers

<img width="788" alt="Screenshot 2021-01-04 at 12 51 31" src="https://user-images.githubusercontent.com/26968615/103532504-a6281f00-4e8b-11eb-923f-4ead6441a0b9.png">


That is handled by https://github.com/w3c/mdn-spec-links -- This is just a nice to have though. Not something we will do right away -- but, if we share data with MDN we will have this ability in the future.

**Comment by septs** [comment]
@codehag we can based stage number and tags, using different ruleset.

**Comment by septs** [comment]
> WARNING: ruleset is an inherit relationship

stage 0:
required field list: `tags`, `name`, `stage`, `authors`, `id`
other optional field, if exists then check it.

stage 1:
required field list: `description`, `champions`, `notes`

stage 2:
required field list: `has-specification`, `tests`

stage 3:
required field list: `tests`, `snippets`

stage 4:
required field list: `edition`

but if set `inactive` / `withdrawn` / `deprecated` / `archived` in tags
required field list: `rationale` field
else not allowed to set `rationale` field

**Comment by codehag** [comment]
One modification: Test262 tests are not merged until a proposal reaches stage 3, so there are stage 3 proposals with no tests. the tests should be required for stage 4.

I am a little torn on snippets. Arguably, we should have snippets for everything, but for some proposals like legacy regex, this is not so interesting for users. But, if this is just something that is encouraged going forward I think that is really good.

**Comment by septs** [comment]
`snippets` move to stage 2?
`tests` move to stage 4?
stage 3 need include ?

**Comment by codehag** [comment]
Snippets can stay at stage 3, as stage 2 is design of the api and may be in flux -- entry into stage 2 is acceptance of the problem. But, also, this is also more a dream of mine rather than something everyone agreed to.

Tests should move to stage 4. Stage 3 would introduce snippets which demonstrate the api that is being implemented (again, in a perfect world)

one issue about stage 4 -- edition will only be agreed to in spring, likely the following year that a proposal is moved to stage 4. Would we eagerly flag stage 4 proposals as (for example) 2022?

stage 2:
required field list: has-specification

stage 3:
required field list: =snippets

stage 4:
required field list: tests, edition

**Comment by septs** [comment]
@codehag about metadata file name problem, any idea?

```
/proposal.json
/metadata.json
```

or otherwise name?

**Comment by codehag** [comment]
This would be metadata in each proposal I suppose? I need to think about that a bit more... let me get back to you on it tomorrow. I am thinking about how webref works and whether we want to do the same thing, as in -- one central repo that crawls all proposals and houses their data. But I haven't thought through all of the consequences yet.

**Comment by septs** [comment]
> stage 4:
> required field list: tests, edition

need include support data?

https://github.com/tc39/dataset/blob/d064501ad1f0acae7504ee3c9fdb038b18e8ec95/schema/individual.json#L121-L124

**Comment by codehag** [comment]
This would be a nice to have... Let's say -- much like the snippets, in a perfect world, yes. So, we can make it required for now to give this a certain vision, though we may need to change things later.

At the moment, we haven't gotten agreement from people that they would do this yet, and we are effectively volunteering people for work. It would be a proposal. But I think it will be well received since people have mentioned that it would be nice to have it elsewhere, and it would help keep mdn content current.

**Comment by septs** [comment]
> it would help keep mdn content current.

mean stage 4 after, we not can archive repository (we need metadata file keep latest)

**Comment by septs** [comment]
@codehag need lint object key order? 
editing costs will increase, but readability will be enhanced

e.g:
1st key name require is `tags`
2nd key name require is `name`
3rd key name require is `authors`
4th key name require is `champions`
etc

**Comment by septs** [comment]
Solution
- JSON Schema Linter
  https://github.com/stoplightio/spectral

**Comment by codehag** [comment]
If we can lint key order, we can probably automatically format it, so that should reduce the editing cost. 

Regarding this comment I made earlier:

> This would be metadata in each proposal I suppose? I need to think about that a bit more... let me get back to you on it tomorrow. I am thinking about how webref works and whether we want to do the same thing, as in -- one central repo that crawls all proposals and houses their data. But I haven't thought through all of the consequences yet.

My feeling now, after thinking for a week, is that we should have all of the data in _this_ repo. Thinking of it from a use perspective we have the following stories:

1) Website -> an automated task that accesses just one repo for all of the info that it needs, rather than each repo separately will be more efficient
2) Repos validating themselves -> Accessing one repo (this one) is about as good as accessing themselves. In any case they would need to also validate against some external entity. This skips that step because we can always keep this up to date.
3) This repo validating against the proposals repo and any other pieces of data  -> the complexity is in one place and has a clear responsibility.

So, to answer the question of what the location should be, I would say that we probably want to keep everything locally here, even for the individual proposals. What do you think?

**Comment by codehag** [comment]
(just a heads up, i might have missed a few things, please ping me on those again and i will get to them today)

**Comment by ljharb** [comment]
If that’s the case, would it make sense to store all the data in the proposals repo, so it remains the only source of truth, and leave this repo for the tooling?

**Comment by codehag** [comment]
Yes, that would also be a good solution

**Comment by septs** [comment]
about `authors` field in some idea.

1. use github username, e.g:
   ```
   "authors": ["@septs"]
   ```
   linter check the username is exists.
2. use email address, e.g:
   ```
   "authors": ["septs <tc39-delegate@septs.email>"]
   ```
   linter check this domain `MX` record exists.
   rfc: https://tools.ietf.org/html/rfc2822
3. use [notes/delegates.txt](https://github.com/tc39/notes/blob/master/delegates.txt), e.g:
   ```
   "authors": ["Jack Works (JWK)"]
   ```
   linter check this string in the delegate list.
4. not allow any string in this field (`authors`)

**Comment by septs** [comment]
@codehag about non github repo proposal any idea?

https://github.com/tc39/dataset/blob/1bb2c49fc8caaf38140c28dc0df050154e1f312c/proposals.json#L3082-L3096

1. ~~1 by 1 create repo~~
2. provide an "pre-dataset" on this dataset (or `tc39/proposals`)
    if someone wants to take over any (cold) proposal, need create repo and delete this record
    (migrate non github repo proposal to github)

**Comment by septs** [comment]
@codehag

**Comment by septs** [comment]
about `rationale` field in some idea.

the current prefix include:

1. `Withdrawn`
2. `Rejected`
3. `Obsoleted`
4. `Inactive`
5. `Never presented`
6. `Postponed`

linter need require limit proposal editor use fixed prefix string in `rationale` field?

**Comment by codehag** [comment]
I see what you mean. The [mixing of specification document name and proposal status](https://github.com/tc39/dataset/blob/master/schema/individual.json#L11-L16) in the tags is, I agree, probably not a great solution. Withdrawn proposals are usually belonging to a given specification etc. 

Maybe that field name should change since rationale can be misunderstood. I would suggest, instead, naming the field "status", and expanding the kind enum to ["inactive", "withdrawn", "archived", "active"], with the prior 3 having an associated "reason". 

```
"status": {
   "kind": "active",
   "reason": ""
}
```

Vs

```
"status": {
   "kind": "withdrawn",
   "reason": "terrible idea"
}
```

The reason we might want to do this (have that extra enum), is that otherwise if we want to get all active proposals, you have to filter out the inactive proposals. This way we would be able to just get all active proposals. wdyt?

**Comment by septs** [comment]
@codehag https://github.com/tc39/dataset/issues/3#issuecomment-760461047 and https://github.com/tc39/dataset/issues/3#issuecomment-760480072
any idea?

**Comment by codehag** [comment]
In https://github.com/tc39/dataset/issues/3#issuecomment-760480072 -- The goal of this, as I see it, would be archival. Option 2 best fits that role. I like option 2. There is a third option which is to do nothing. Both would be fine. 

For https://github.com/tc39/dataset/issues/3#issuecomment-760480072 -- The goal of this is to identify the key people responsible for a proposal. This is a bit more complicated -- should people be contactable? What about people from outside of github? etc.

I thought about this in a few different directions. Not everyone has github, or is active on github, and we cannot be sure we will use github forever. So i don't think we should use github user names. Emails are complicated -- we may open up people to being contacted without their consent (this is especially a problem if people get angry about something). A third option I thought of is to use this list: https://github.com/tc39/notes/blob/master/delegates.txt -- but, authors can be anyone, not necessarily only delegates. 

I don't have a good answer here. I would suggest to have it be a simple string, which reflects what is present on the repo. The primary contact point for work on a proposal should be within the context of of the proposal repo anyway. 

Are there some other ideas that you have about this field?

**Comment by ljharb** [comment]
If we leave GitHub, we could capture user emails then; having GitHub to participate is already a requirement (and imo a reasonable one). Although there could be authors that don’t use GitHub, it hasn’t happened yet, and I’d find it surprising.

**Comment by septs** [comment]
> The goal of this is to identify the key people responsible for a proposal. This is a bit more complicated -- should people be contactable? What about people from outside of github? etc.

1. author lost contact, does it mean the inactive / cold of the proposal?

2. 100% rejected to use github, how to participate in tc39 collaboration?

CC @codehag

**Comment by codehag** [comment]
Both cases outlined by septs are possibilties. The second so far hasn't happened but it isn't impossible. I wouldn't find it surprising, given the political climate, some TC39 members have moved almost entirely off github such as inria. They still participate, but they are taking a stand. I don't think we should consider github as a certainty.

That said, if there is a clear migration path, maybe it will be simpler. I guess we come back to the question of 'what is the goal'. The goal is to know who to talk to. From my perspective, I find that the name is easiest to search for without giving away too much contact information. 

We can just have extra data, and make this an array of objects with multiple fields. As an idea? What is most useful?

```
{
  name: "..."
  github: "..."
}
```

**Comment by Jack-Works** [comment]
Emails look good, it's fully decentralized

**Comment by codehag** [comment]
My main worry regarding email is harassment, especially of minorities, though I suppose there is no way to fully protect against this and emails on github are publicly available (though obscured) anyway. I am happy having extra information in this field.

**Comment by septs** [comment]
tc39 may can provide email forwarding service on delegate and stage 1+ authors

e.g: `<username>@users.noreply.tc39.es` forward to personal / company / (etc) email address

like https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Comment by septs** [comment]
authors field new format, my idea:

```json
"authors": [
    { "nickname": "Example", "email": "example@example.com", "github": "Example" },
    { "delegate": "Jack Works (JWK)" }
]
```

**Comment by codehag** [comment]
Would those be two separate entries or the same entry?

**Comment by septs** [comment]
> Would those be two separate entries or the same entry?

two a type (entry)

**Comment by codehag** [comment]
Ah, I see -- would you say that the non-delegate role fields are optional for the delegate? 

For the non-delegate role, would it make sense to have a formal name? Or maybe call it just name, and if someone has a chosen name it goes in that field?

**Comment by codehag** [comment]
Now that I am thinking about it more, I think we should have just one type of field and not distinguish between delegates and authors.

**Comment by ljharb** [comment]
GitHub users who want to keep their email private are furnished with a forwarding address, and that would show up on their profile - so i think it’s a safe assumption that if an email address is on a GitHub profile, it’s intentionally public.

**Comment by codehag** [comment]
Ok, I think we can just have a combined field here.

**Comment by septs** [comment]
> Ok, I think we can just have a combined field here.

how to you want to design the `authors` field?

**Comment by codehag** [comment]
I liked your suggestion (with a small modification, nickname -> name)

```
"authors": [
    { "name": "Example", "email": "example@example.com", "github": "Example" },
    ]
```
but for both delegates and non-delegates.

**Comment by septs** [comment]
how to to identify him is delegate role?

e.g: delegate deliberately does not use the `delegate` name in the `name` field.

```jsonc
"authors": [
    { "name": "Example", "email": "example@example.com", "github": "Example" }, // non delegate role
    { "name": "Example", "email": "example@example.com", "github": "Example", "delegate": false }, // delegate role
]
```

e.g: if delegate is true then check name is in `notes/delegates.txt`

**Comment by codehag** [comment]
For this field, do we need to know that the person is a delegate? I am wondering if the distinction makes sense. Champions need to be delegates, but for authors it can really be anyone.

**Comment by codehag** [comment]
(the bool flag makes sense though, if we do have a use case for distinguishing between delegates and non-delegates. I just can't think of one)

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/106573542-bc052e80-6574-11eb-9171-0cb1df4ca3c6.png)

from https://github.com/tc39/proposals

**Comment by septs** [comment]
CC @Jack-Works @hax any idea?

**Comment by codehag** [comment]
Hmm, maybe I am not understanding the issue you are raising? Is it that sometimes the author and the champion is the same?

**Comment by septs** [comment]
https://github.com/w3c/spec-prod

--------

This is a memo
